import { mutation } from "./_generated/server";

export const seedMedicines = mutation({
  args: {},
  handler: async (ctx) => {
    const medicines = [
      // Pain Relief & Headache
      {
        name: "Paracetamol 500mg",
        description: "Effective pain relief and fever reducer. Safe for adults and children.",
        price: 15,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "PharmaCorp",
        dosage: "500mg tablets",
        quantity: 100,
      },
      {
        name: "Ibuprofen 400mg",
        description: "Anti-inflammatory medication for pain, fever, and inflammation.",
        price: 35,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "MediHealth",
        dosage: "400mg tablets",
        quantity: 100,
      },
      {
        name: "Aspirin 75mg",
        description: "Low-dose aspirin for pain relief and cardiovascular protection.",
        price: 25,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "CardioHealth",
        dosage: "75mg tablets",
        quantity: 100,
      },
      {
        name: "Diclofenac 50mg",
        description: "Strong anti-inflammatory for joint pain and arthritis.",
        price: 45,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "JointCare",
        dosage: "50mg tablets",
        quantity: 80,
      },
      {
        name: "Naproxen 250mg",
        description: "Long-lasting pain relief for arthritis and muscle pain.",
        price: 65,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "PainAway",
        dosage: "250mg tablets",
        quantity: 60,
      },
      {
        name: "Tramadol 50mg",
        description: "Moderate to severe pain management.",
        price: 85,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "PainCare",
        dosage: "50mg capsules",
        quantity: 50,
      },
      {
        name: "Celecoxib 200mg",
        description: "COX-2 inhibitor for arthritis pain.",
        price: 120,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Pain Relief",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "ArthriCare",
        dosage: "200mg capsules",
        quantity: 40,
      },
      {
        name: "Sumatriptan 50mg",
        description: "Prescription-strength migraine treatment.",
        price: 180,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Headache",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "MigraineAway",
        dosage: "6 tablets",
        quantity: 30,
      },
      {
        name: "Rizatriptan 10mg",
        description: "Fast-dissolving migraine relief tablets.",
        price: 165,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Headache",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "HeadacheFree",
        dosage: "6 tablets",
        quantity: 35,
      },
      {
        name: "Ergotamine 1mg",
        description: "Effective for cluster headaches and migraines.",
        price: 125,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Headache",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "NeuroMed",
        dosage: "12 tablets",
        quantity: 40,
      },
      {
        name: "Topiramate 25mg",
        description: "Preventive treatment for chronic migraines.",
        price: 220,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Headache",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "PreventMed",
        dosage: "30 tablets",
        quantity: 25,
      },
      {
        name: "DOLO 650",
        description: "Effective relief from headache, fever, and body pain.",
        price: 30,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Headache",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "Micro Labs",
        dosage: "650mg tablets",
        quantity: 150,
      },
      
      // Digestion
      {
        name: "Omeprazole 20mg",
        description: "Reduces stomach acid production for GERD and ulcers.",
        price: 35,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "GastroMed",
        dosage: "14 capsules",
        quantity: 100,
      },
      {
        name: "Loperamide 2mg",
        description: "Effective treatment for diarrhea and stomach upset.",
        price: 45,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "DigestEase",
        dosage: "12 tablets",
        quantity: 90,
      },
      {
        name: "Ranitidine 150mg",
        description: "H2 blocker for acid reflux and heartburn.",
        price: 55,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AcidControl",
        dosage: "30 tablets",
        quantity: 80,
      },
      {
        name: "Pantoprazole 40mg",
        description: "Proton pump inhibitor for severe acid reflux.",
        price: 85,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "GastroShield",
        dosage: "15 tablets",
        quantity: 70,
      },
      {
        name: "Esomeprazole 20mg",
        description: "Long-lasting relief from acid reflux.",
        price: 95,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "RefluxAway",
        dosage: "14 capsules",
        quantity: 65,
      },
      {
        name: "Bismuth Subsalicylate 262mg",
        description: "Treats upset stomach, diarrhea, and nausea.",
        price: 95,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "StomachCare",
        dosage: "30 tablets",
        quantity: 75,
      },
      {
        name: "Simethicone 125mg",
        description: "Gas relief and bloating reduction.",
        price: 75,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "GasRelief",
        dosage: "24 softgels",
        quantity: 85,
      },
      {
        name: "Famotidine 20mg",
        description: "Acid reducer for heartburn prevention.",
        price: 145,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "HeartburnFree",
        dosage: "30 tablets",
        quantity: 60,
      },
      {
        name: "Metoclopramide 10mg",
        description: "Treats nausea and improves gastric emptying.",
        price: 175,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "NauseaAway",
        dosage: "30 tablets",
        quantity: 50,
      },
      {
        name: "Ondansetron 4mg",
        description: "Prevents nausea and vomiting.",
        price: 285,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "AntiNausea",
        dosage: "10 tablets",
        quantity: 40,
      },
      {
        name: "Sucralfate 1g",
        description: "Protects stomach lining and treats ulcers.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "UlcerCare",
        dosage: "60 tablets",
        quantity: 45,
      },
      {
        name: "Mebeverine 135mg",
        description: "Relieves IBS symptoms and abdominal cramps.",
        price: 165,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Digestion",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "IBSCare",
        dosage: "30 tablets",
        quantity: 55,
      },
      
      // Vitamins & Supplements
      {
        name: "Vitamin C 1000mg",
        description: "Immune system support and antioxidant protection.",
        price: 120,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "VitaBoost",
        dosage: "60 tablets",
        quantity: 120,
      },
      {
        name: "Vitamin D3 2000IU",
        description: "Supports bone health and immune function.",
        price: 340,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "BoneStrong",
        dosage: "60 capsules",
        quantity: 100,
      },
      {
        name: "Vitamin B Complex",
        description: "Energy metabolism and nervous system support.",
        price: 295,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "EnergyPlus",
        dosage: "100 tablets",
        quantity: 90,
      },
      {
        name: "Vitamin E 400IU",
        description: "Antioxidant protection for skin and cells.",
        price: 325,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "SkinVita",
        dosage: "60 softgels",
        quantity: 85,
      },
      {
        name: "Zinc 50mg",
        description: "Immune support and wound healing.",
        price: 215,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "ImmuneBoost",
        dosage: "100 tablets",
        quantity: 110,
      },
      {
        name: "Magnesium 400mg",
        description: "Muscle relaxation and sleep support.",
        price: 285,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "RelaxMag",
        dosage: "90 capsules",
        quantity: 95,
      },
      {
        name: "Iron 65mg",
        description: "Prevents and treats iron deficiency anemia.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "IronPlus",
        dosage: "100 tablets",
        quantity: 105,
      },
      {
        name: "Biotin 10000mcg",
        description: "Hair, skin, and nail health support.",
        price: 365,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "BeautyVita",
        dosage: "120 capsules",
        quantity: 80,
      },
      {
        name: "Folic Acid 800mcg",
        description: "Essential for pregnancy and cell growth.",
        price: 175,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "PreNatal",
        dosage: "90 tablets",
        quantity: 115,
      },
      {
        name: "Vitamin K2 100mcg",
        description: "Bone and cardiovascular health.",
        price: 395,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "HeartBone",
        dosage: "60 capsules",
        quantity: 70,
      },
      {
        name: "Coenzyme Q10 200mg",
        description: "Cellular energy and heart health.",
        price: 685,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "CellEnergy",
        dosage: "60 softgels",
        quantity: 60,
      },
      {
        name: "Melatonin 5mg",
        description: "Sleep aid and circadian rhythm support.",
        price: 245,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Vitamins",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "SleepWell",
        dosage: "60 tablets",
        quantity: 100,
      },
      
      // Cold & Flu
      {
        name: "Pseudoephedrine 60mg",
        description: "Powerful nasal decongestant.",
        price: 125,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Cold & Flu",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "ClearNose",
        dosage: "24 tablets",
        quantity: 80,
      },
      {
        name: "Phenylephrine 10mg",
        description: "Non-drowsy decongestant.",
        price: 115,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Cold & Flu",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "SinusClear",
        dosage: "30 tablets",
        quantity: 90,
      },
      {
        name: "Guaifenesin 400mg",
        description: "Expectorant for chest congestion.",
        price: 135,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Cold & Flu",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "ChestRelief",
        dosage: "20 tablets",
        quantity: 85,
      },
      {
        name: "Dextromethorphan 30mg",
        description: "Cough suppressant for dry cough.",
        price: 145,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Cold & Flu",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "CoughStop",
        dosage: "20 capsules",
        quantity: 75,
      },
      
      // Allergy
      {
        name: "Cetirizine 10mg",
        description: "Non-drowsy antihistamine for allergy symptoms.",
        price: 25,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AllergyShield",
        dosage: "30 tablets",
        quantity: 120,
      },
      {
        name: "Loratadine 10mg",
        description: "24-hour non-drowsy allergy relief.",
        price: 175,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "ClarityCare",
        dosage: "30 tablets",
        quantity: 100,
      },
      {
        name: "Fexofenadine 180mg",
        description: "Fast-acting allergy medication.",
        price: 215,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AllergyFast",
        dosage: "30 tablets",
        quantity: 90,
      },
      {
        name: "Diphenhydramine 25mg",
        description: "Antihistamine for allergies and sleep aid.",
        price: 95,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "HistaBlock",
        dosage: "24 capsules",
        quantity: 110,
      },
      {
        name: "Montelukast 10mg",
        description: "Leukotriene blocker for allergies and asthma.",
        price: 325,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BreatheFree",
        dosage: "30 tablets",
        quantity: 70,
      },
      {
        name: "Chlorpheniramine 4mg",
        description: "Classic antihistamine for allergies.",
        price: 85,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AllerOld",
        dosage: "24 tablets",
        quantity: 95,
      },
      {
        name: "Desloratadine 5mg",
        description: "Advanced non-drowsy antihistamine.",
        price: 235,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Allergy",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AllerAdvanced",
        dosage: "30 tablets",
        quantity: 85,
      },
      
      // Diabetes
      {
        name: "Metformin 500mg",
        description: "Blood sugar control for type 2 diabetes.",
        price: 25,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "DiabetCare",
        dosage: "60 tablets",
        quantity: 150,
      },
      {
        name: "Glimepiride 2mg",
        description: "Helps lower blood sugar levels in diabetes patients.",
        price: 220,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "SugarControl",
        dosage: "30 tablets",
        quantity: 80,
      },
      {
        name: "Gliclazide 80mg",
        description: "Sulfonylurea for type 2 diabetes.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "GlucoMed",
        dosage: "30 tablets",
        quantity: 75,
      },
      {
        name: "Sitagliptin 100mg",
        description: "DPP-4 inhibitor for diabetes management.",
        price: 485,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "DiabetPlus",
        dosage: "30 tablets",
        quantity: 60,
      },
      {
        name: "Pioglitazone 30mg",
        description: "Improves insulin sensitivity.",
        price: 325,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "InsulinCare",
        dosage: "30 tablets",
        quantity: 65,
      },
      {
        name: "Empagliflozin 10mg",
        description: "SGLT2 inhibitor for diabetes and heart health.",
        price: 595,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "HeartDiabet",
        dosage: "30 tablets",
        quantity: 50,
      },
      {
        name: "Dapagliflozin 10mg",
        description: "Reduces blood sugar and protects kidneys.",
        price: 565,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Diabetes",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "KidneyGuard",
        dosage: "30 tablets",
        quantity: 55,
      },
      
      // Blood Pressure
      {
        name: "Amlodipine 5mg",
        description: "Calcium channel blocker for high blood pressure.",
        price: 20,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "CardioMed",
        dosage: "30 tablets",
        quantity: 140,
      },
      {
        name: "Losartan 50mg",
        description: "Angiotensin receptor blocker for hypertension.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "HeartCare",
        dosage: "30 tablets",
        quantity: 90,
      },
      {
        name: "Atenolol 50mg",
        description: "Beta-blocker for blood pressure and heart conditions.",
        price: 125,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BPControl",
        dosage: "30 tablets",
        quantity: 100,
      },
      {
        name: "Lisinopril 10mg",
        description: "ACE inhibitor for hypertension.",
        price: 165,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "PressureDown",
        dosage: "30 tablets",
        quantity: 95,
      },
      {
        name: "Telmisartan 40mg",
        description: "ARB for blood pressure control.",
        price: 215,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "TensionFree",
        dosage: "30 tablets",
        quantity: 85,
      },
      {
        name: "Metoprolol 50mg",
        description: "Beta-blocker for hypertension and angina.",
        price: 175,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "HeartBeat",
        dosage: "30 tablets",
        quantity: 90,
      },
      {
        name: "Ramipril 5mg",
        description: "ACE inhibitor for heart and kidney protection.",
        price: 185,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Blood Pressure",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "CardioShield",
        dosage: "30 tablets",
        quantity: 80,
      },
      
      // Antibiotics
      {
        name: "Amoxicillin 500mg",
        description: "Broad-spectrum antibiotic for bacterial infections.",
        price: 45,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "InfectAway",
        dosage: "21 capsules",
        quantity: 100,
      },
      {
        name: "Azithromycin 500mg",
        description: "Antibiotic for respiratory and skin infections.",
        price: 85,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BacteriaFree",
        dosage: "6 tablets",
        quantity: 80,
      },
      {
        name: "Ciprofloxacin 500mg",
        description: "Fluoroquinolone antibiotic for various infections.",
        price: 210,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "InfectionCure",
        dosage: "10 tablets",
        quantity: 70,
      },
      {
        name: "Doxycycline 100mg",
        description: "Tetracycline antibiotic for infections and acne.",
        price: 165,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BacterStop",
        dosage: "20 capsules",
        quantity: 75,
      },
      {
        name: "Cephalexin 500mg",
        description: "Cephalosporin antibiotic for skin and respiratory infections.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "CephaCure",
        dosage: "28 capsules",
        quantity: 65,
      },
      {
        name: "Levofloxacin 500mg",
        description: "Broad-spectrum fluoroquinolone antibiotic.",
        price: 285,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "LevaFight",
        dosage: "10 tablets",
        quantity: 60,
      },
      {
        name: "Clindamycin 300mg",
        description: "Antibiotic for serious bacterial infections.",
        price: 325,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "ClindaCure",
        dosage: "16 capsules",
        quantity: 55,
      },
      {
        name: "Metronidazole 400mg",
        description: "Antibiotic for anaerobic bacterial and protozoal infections.",
        price: 145,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Antibiotics",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "MetroMed",
        dosage: "21 tablets",
        quantity: 85,
      },
      
      // Skin Care
      {
        name: "Hydrocortisone Cream 1%",
        description: "Anti-inflammatory cream for skin irritation and rashes.",
        price: 155,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "DermaCare",
        dosage: "30g tube",
        quantity: 90,
      },
      {
        name: "Tretinoin Cream 0.025%",
        description: "Retinoid for acne and anti-aging.",
        price: 385,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "RetinCare",
        dosage: "20g tube",
        quantity: 60,
      },
      {
        name: "Clotrimazole Cream 1%",
        description: "Antifungal for yeast infections and ringworm.",
        price: 145,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "FungalFree",
        dosage: "30g tube",
        quantity: 85,
      },
      {
        name: "Adapalene Gel 0.1%",
        description: "Retinoid for acne treatment.",
        price: 295,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "DiffCare",
        dosage: "30g tube",
        quantity: 75,
      },
      {
        name: "Mupirocin Ointment 2%",
        description: "Antibiotic ointment for skin infections.",
        price: 225,
        imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BacterDerm",
        dosage: "15g tube",
        quantity: 70,
      },
      {
        name: "Ketoconazole Cream 2%",
        description: "Antifungal for seborrheic dermatitis.",
        price: 245,
        imageUrl: "https://images.unsplash.com/photo-1550572017-4a6e8c4f8f6f?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "KetoSkin",
        dosage: "30g tube",
        quantity: 80,
      },
      {
        name: "Betamethasone Cream 0.1%",
        description: "Potent corticosteroid for skin inflammation.",
        price: 195,
        imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: true,
        manufacturer: "BetaDerm",
        dosage: "30g tube",
        quantity: 65,
      },
      {
        name: "Azelaic Acid 10%",
        description: "Treatment for acne and hyperpigmentation.",
        price: 365,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
        category: "Skin Care",
        inStock: true,
        requiresPrescription: false,
        manufacturer: "AzelaClear",
        dosage: "30g tube",
        quantity: 70,
      },
    ];

    for (const medicine of medicines) {
      await ctx.db.insert("medicines", medicine);
    }

    return { success: true, count: medicines.length };
  },
});

export const seedPharmacies = mutation({
  args: {},
  handler: async (ctx) => {
    const pharmacies = [
      // Bangalore - Central Areas
      {
        name: "Apollo Pharmacy",
        address: "MG Road, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560001",
        latitude: 12.9716,
        longitude: 77.5946,
        phone: "+91 80 2558 1234",
        isActive: true,
      },
      {
        name: "MedPlus Pharmacy",
        address: "Indiranagar, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560038",
        latitude: 12.9784,
        longitude: 77.6408,
        phone: "+91 80 2521 5678",
        isActive: true,
      },
      {
        name: "Wellness Forever",
        address: "Koramangala, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560034",
        latitude: 12.9352,
        longitude: 77.6245,
        phone: "+91 80 4112 3456",
        isActive: true,
      },
      {
        name: "Netmeds Pharmacy",
        address: "Jayanagar, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560041",
        latitude: 12.9250,
        longitude: 77.5838,
        phone: "+91 80 2663 7890",
        isActive: true,
      },
      {
        name: "1mg Store",
        address: "Whitefield, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560066",
        latitude: 12.9698,
        longitude: 77.7499,
        phone: "+91 80 6789 1234",
        isActive: true,
      },
      {
        name: "HealthBuddy Pharmacy",
        address: "Electronic City, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560100",
        latitude: 12.8456,
        longitude: 77.6603,
        phone: "+91 80 2852 4567",
        isActive: true,
      },
      {
        name: "PharmEasy Store",
        address: "HSR Layout, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560102",
        latitude: 12.9121,
        longitude: 77.6446,
        phone: "+91 80 4567 8901",
        isActive: true,
      },
      {
        name: "Cure Plus Pharmacy",
        address: "Malleshwaram, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560003",
        latitude: 13.0067,
        longitude: 77.5703,
        phone: "+91 80 2334 5678",
        isActive: true,
      },
      {
        name: "LifeCare Pharmacy",
        address: "BTM Layout, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560076",
        latitude: 12.9165,
        longitude: 77.6101,
        phone: "+91 80 2678 9012",
        isActive: true,
      },
      {
        name: "MediHub 24x7",
        address: "Marathahalli, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560037",
        latitude: 12.9591,
        longitude: 77.6974,
        phone: "+91 80 4123 4567",
        isActive: true,
      },
      {
        name: "QuickHeal Pharmacy",
        address: "Banashankari, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560070",
        latitude: 12.9250,
        longitude: 77.5482,
        phone: "+91 80 2661 2345",
        isActive: true,
      },
      {
        name: "CityMed Pharmacy",
        address: "Rajajinagar, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560010",
        latitude: 12.9916,
        longitude: 77.5522,
        phone: "+91 80 2331 6789",
        isActive: true,
      },
      {
        name: "HealthFirst Pharmacy",
        address: "Yelahanka, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560064",
        latitude: 13.1007,
        longitude: 77.5963,
        phone: "+91 80 2846 7890",
        isActive: true,
      },
      {
        name: "MediCare Plus",
        address: "JP Nagar, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560078",
        latitude: 12.9081,
        longitude: 77.5858,
        phone: "+91 80 2659 3456",
        isActive: true,
      },
      {
        name: "WellnessRx Pharmacy",
        address: "Hebbal, Bangalore",
        city: "Bangalore",
        state: "Karnataka",
        zipCode: "560024",
        latitude: 13.0358,
        longitude: 77.5970,
        phone: "+91 80 2345 6789",
        isActive: true,
      },
      
      // Karnataka - Other Cities
      {
        name: "Apollo Pharmacy",
        address: "MG Road, Mysore",
        city: "Mysore",
        state: "Karnataka",
        zipCode: "570001",
        latitude: 12.2958,
        longitude: 76.6394,
        phone: "+91 821 242 3456",
        isActive: true,
      },
      {
        name: "MedPlus Pharmacy",
        address: "Sayyaji Rao Road, Mysore",
        city: "Mysore",
        state: "Karnataka",
        zipCode: "570001",
        latitude: 12.3051,
        longitude: 76.6553,
        phone: "+91 821 244 5678",
        isActive: true,
      },
      {
        name: "HealthCare Pharmacy",
        address: "Nehru Road, Mangalore",
        city: "Mangalore",
        state: "Karnataka",
        zipCode: "575001",
        latitude: 12.9141,
        longitude: 74.8560,
        phone: "+91 824 242 7890",
        isActive: true,
      },
      {
        name: "CityMed Pharmacy",
        address: "Hampankatta, Mangalore",
        city: "Mangalore",
        state: "Karnataka",
        zipCode: "575001",
        latitude: 12.8698,
        longitude: 74.8430,
        phone: "+91 824 244 1234",
        isActive: true,
      },
      {
        name: "Wellness Pharmacy",
        address: "Station Road, Hubli",
        city: "Hubli",
        state: "Karnataka",
        zipCode: "580020",
        latitude: 15.3647,
        longitude: 75.1240,
        phone: "+91 836 223 4567",
        isActive: true,
      },
      {
        name: "MediPlus Store",
        address: "College Road, Belgaum",
        city: "Belgaum",
        state: "Karnataka",
        zipCode: "590001",
        latitude: 15.8497,
        longitude: 74.4977,
        phone: "+91 831 242 6789",
        isActive: true,
      },
      {
        name: "LifeLine Pharmacy",
        address: "Gandhi Nagar, Gulbarga",
        city: "Gulbarga",
        state: "Karnataka",
        zipCode: "585101",
        latitude: 17.3297,
        longitude: 76.8343,
        phone: "+91 8472 22 3456",
        isActive: true,
      },
      {
        name: "QuickMeds Pharmacy",
        address: "Main Road, Davangere",
        city: "Davangere",
        state: "Karnataka",
        zipCode: "577001",
        latitude: 14.4644,
        longitude: 75.9218,
        phone: "+91 8192 22 5678",
        isActive: true,
      },
      {
        name: "HealthPlus Pharmacy",
        address: "KR Circle, Shimoga",
        city: "Shimoga",
        state: "Karnataka",
        zipCode: "577201",
        latitude: 13.9299,
        longitude: 75.5681,
        phone: "+91 8182 22 7890",
        isActive: true,
      },
      {
        name: "Apollo Pharmacy",
        address: "Court Road, Tumkur",
        city: "Tumkur",
        state: "Karnataka",
        zipCode: "572101",
        latitude: 13.3392,
        longitude: 77.1006,
        phone: "+91 816 227 1234",
        isActive: true,
      },
    ];

    for (const pharmacy of pharmacies) {
      await ctx.db.insert("pharmacies", pharmacy);
    }

    return { success: true, count: pharmacies.length };
  },
});